name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Set up Git to use PAT for GitHub
            env:
             GH_PAT: ${{ secrets.GH_PAT }}

            run: |
             git config --global url."https://x-access-token:${GH_PAT}@github.com/".insteadOf "https://github.com/"
          - name: Run full test
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
